name             'generic_nodejs'
maintainer       'evalonlabs'
maintainer_email 'epapas@evalonlabs.com'
license          'Apache 2.0'
description      'Installs/Configures generic_nodejs'
long_description 'Installs/Configures generic_nodejs'
version          '0.1.0'

depends 'build-essential'
depends 'openssl'
depends 'couchdb'
depends 'nodejs'
depends 'redisio'
depends 'chef-client'
depends 'git'
depends 'iptables'